### ISSUE TITLE
Allow searching by month or year

### ISSUE THREAD

**Issue by TheRustyPickle** [TheRustyPickle/Rex#25]
Currently, the search page can only handle an exact day. Being able to search for tx on a specific month of a year or a year would be useful.

**Comment by vlad-onis** [comment]
Hello I'd like to try to tackle this during this weekend! If you want you can assign  it to me and I'll see what I can do.
Great project btw, congrats!

**Comment by TheRustyPickle** [comment]
I highly appreciate your interest in taking it on, @vlad-onis! Feel free to work on it. If you have any questions, confusion, or suggestion on tackling this, let me know. Before you get started, below are some of the things you might want to know.

Quite a few components such as the UI, value stepper, and date verifier need to be changed for it to work properly. You don't have to do everything at once and can do a partial contribution toward the competition of it. 

For the UI, I initially thought about adding a keypress to take a different Date input (Cycle between exact date, monthly, yearly). If you have a better approach to it, I would be happy to hear about it!

**Comment by vlad-onis** [comment]
Hello, I will have to postpone this a bit due to a few things I have to take care of. I will take on of the other issue in the following days which are quicker to solve and I will get myself familiarized with the codebase. Srry I did not manage to work on it this weekend as promised.

**Comment by TheRustyPickle** [comment]
No problem! Thanks for keeping me posted.

**Comment by TheRustyPickle** [comment]
Closed on #38
