### ISSUE TITLE
Project logo/image

### ISSUE THREAD

**Issue by TheRustyPickle** [TheRustyPickle/Rex#30]
The project currently lacks any kind of logo or image. It would be really nice to have one. If anyone wants to contribute toward this, I would be happy to accept it!

**Comment by vlad-onis** [comment]
I am an engineer with sane defaults. That means i cannot draw, but midjourney can.

I thought Rex comes from Rust expenses and i generated a few rich Ferries, let me know wdyt and i can vary them a bit.

![image](https://github.com/TheRustyPickle/Rex/assets/107788332/07fb4663-4502-42fc-ae30-dd1520818f19)

![image](https://github.com/TheRustyPickle/Rex/assets/107788332/1d5509fa-0ac7-4740-9dbc-cfc4d09aa528)

![image](https://github.com/TheRustyPickle/Rex/assets/107788332/4168d672-e288-4623-831d-4c4d7770501f)

![image](https://github.com/TheRustyPickle/Rex/assets/107788332/d2e927b7-94a4-43a1-a20c-d19a2228d7f5)

**Comment by TheRustyPickle** [comment]
These look really good! Thank you so much for going through the effort, @vlad-onis! I like the first one.

**Comment by TheRustyPickle** [comment]
Already added it to the readme. Highly appreciate your contribution to it!
