### ISSUE TITLE
Logo again

### ISSUE THREAD

**Issue by vlad-onis** [TheRustyPickle/Rex#33]
I took the one you liked and made it round and removed background. Let me know if it is better!
![image](https://github.com/TheRustyPickle/Rex/assets/107788332/7d26cdfa-fddc-4054-b74f-32166787c338)

**Comment by vlad-onis** [comment]
It is not ideal to have it
![Screenshot from 2023-07-20 13-25-55](https://github.com/TheRustyPickle/Rex/assets/107788332/237c8132-0231-4fe3-b606-f6ce415bc6e2)
 with background. See below

**Comment by vlad-onis** [comment]
And without background...
![Screenshot from 2023-07-20 13-27-15](https://github.com/TheRustyPickle/Rex/assets/107788332/ef74a533-c5a8-4f17-a0ed-fed7303ff631)

**Comment by vlad-onis** [comment]
I recommend trhat you make it a bit smaller before adding it as well, but depends on how you like it more

**Comment by TheRustyPickle** [comment]
Thank you for all this! I didn't check with the dark theme. Feel free to open a PR with the changes with your recommended image size. If you want to improve some other parts of the readme along with this, feel free to do it! I highly appreciate the effort!
